name:                cuesplit-hs
version:             0.1.0.0
github:              "BlackSoulSeller/cuesplit-hs"
license:             MIT
author:              "Marcin Czerwonka"
maintainer:          "mcmarcinoser5@gmail.com"
copyright:           "2019 Marcin Czerwonka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BlackSoulSeller/cuesplit-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  cuesplit-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cuesplit-hs

tests:
  cuesplit-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cuesplit-hs
